### ISSUE TITLE
Override SMART route names

### ISSUE THREAD

**Issue by ivyrze** [jmcbroom/multi-gtfs-gatsby#22]
As you likely well know, SMART's GTFS data unfortunately provides undescriptive and inconsistent route names. The correct ones are below. I've also included the classification per the color on the [system map](https://www.smartbus.org/Portals/0/System%20Maps/2022%20Web%20System%20Map%201-3-22.pdf?ver=EkmMr0OQtzg9aiAMsWtBkA%3d%3d), but I don't think it's the most coherent, so maybe not fully necessary.

| Route | Name                             | Classification |
|-------|----------------------------------|----------------|
| 125   | Fort-Eureka                      | main           |
| 140   | Southshore                       | crosstown      |
| 160   | Downriver                        | community      |
| 200   | Michigan Local                   | main           |
| 210   | Michigan Local-Westland          | main           |
| 250   | Ford                             | crosstown      |
| 255   | Ford Express                     | commuter       |
| 261   | Fast Michigan                    | fast           |
| 275   | Telegraph-Taylor                 | crosstown      |
| 280   | Western Wayne Crosstown          | community      |
| 305   | Grand River                      | crosstown      |
| 375   | Telegraph-Pontiac                | crosstown      |
| 400   | Southfield-Orchard Ridge         | community      |
| 405   | Northwestern Highway             | crosstown      |
| 415   | Greenfield                       | community      |
| 420   | Southfield                       | community      |
| 430   | Main St-Big Beaver           | community      |
| 450   | Woodward Local                   | main           |
| 460   | Woodward Local-Royal Oak         | main           |
| 461   | Fast Woodward-Somerset           | fast           |
| 462   | Fast Woodward-GLCX               | fast           |
| 494   | Dequindre                        | community      |
| 495   | John R                           | community      |
| 510   | Van Dyke                         | main           |
| 525   | Groesbeck                        | community      |
| 530   | Schoenherr                       | commuter       |
| 550   | Garfield                         | community      |
| 560   | Gratiot                          | main           |
| 562   | Fast Gratiot                     | fast           |
| 563   | Fast Gratiot-WSU                 | fast           |
| 610   | Kerchval-Harper                  | main           |
| 615   | Jefferson                        | community      |
| 620   | Charlevoix                       | commuter       |
| 635   | East Jefferson                | commuter       |
| 710   | Nine Mile                        | crosstown      |
| 730   | Ten Mile                         | crosstown      |
| 740   | Twelve Mile                      | crosstown      |
| 760   | Thirteen/Fourteen Mile           | crosstown      |
| 780   | Fifteen Mile                     | crosstown      |
| 790   | Pontiac Crosstown                | crosstown      |
| 796   | Pontiac-Perry-Opdyke             | main           |
| 805   | Grand River P&R                  | park-and-ride  |
| 830   | Downriver P&R                    | park-and-ride  |
| 851   | West Bloomfield P&R              | park-and-ride  |

**Comment by jmcbroom** [comment]
Thanks for opening this up @ivyrze -- those classification types are going to be helpful.

I've emailed SMART about this, suggesting some specific changes to the GTFS, but as of yet they have not implemented those. Perhaps showing them what could be possible will encourage them!

This is a specific instance of a larger problem, namely, that the GTFS data we receive needs work before we can publish it.

I see two ways we could go about this:

1. Post-ingestion scripts on the database + extending the database itself
2. Overriding these with some other source for this content

## option 1: edit/extend database

this could really just be a file of SQL statements that look like

```sql
UPDATE gtfs.routes 
  SET route_long_name = 'Charlevoix' 
  WHERE route_short_name ='620' 
  AND feed_index in 
(
  SELECT 
    feed_index 
  FROM feed_info 
  WHERE feed_publisher_name = 'SMART'
)
```

This was basically the strategy with an earlier attempt at creating this site: 
https://github.com/jmcbroom/all-transit/

We imported route data into [Google Sheets](https://docs.google.com/spreadsheets/d/1Hq-ushnU46MpGYhjW34y8kGhXMKtnxwx2DzGnslxM1g/edit?usp=sharing), edited values like , and then used those values to generate SQL `UPDATE` statements in the database - particularly to set the `timepoint` values for all agencies, which at that time did not yet publish this field. (You can find most of these queries in that repo's [wiki](https://github.com/jmcbroom/all-transit/wiki)).

Similarly, to solve this problem, we could run a bunch of `UPDATE` statements in the DB when we come across those things, and run them in a scriptable way.

## option 2: new source of content

Option 2 would involve building a new data structure that operated in parallel with the underlying GTFS data.

We do this in ddot.info with all the files in the `data` [directory](https://github.com/CityOfDetroit/ddot-info/tree/main/src/data); we have a few .json files which are combined by the various .js files in that folder to generate, say, a GeoJSON feature collection which is suitable to use on the map. the way I've solved this in ddot.info, though, is not super scalable - I'm hand-editing the GeoJSON files when there is a service change, it's not very fun.

an ambitious solution here would be to use a custom CMS to provide a nicer editing interface for this data. We can use [Sanity.io](https://www.sanity.io/) to create a custom schema, to store all the information about a route that we want to be able to easily change, that doesn't have a natural home in GTFS/the database. After creating that custom schema, we'd load in all the routes, edit the names there, and then we'd pull that into the Gatsby build as an additional source of content.

## conclusion

(that was a lot of words, sorry, but helpful to summarize my thoughts about this and hopefully some more helpful background for contributors to this project since we've solved this problem a few ways before)

Let's look at the feasibility of (2) for this narrow purpose. If it's relatively easy to spin up then we can think about more things that it will enable us to do.

If it takes too much time, let's fall back to option (1) in a better way than we've done previously.

next steps:
- create a basic Sanity data model & project for this
- import SMART routes into that data model, attaching the more presentable names compiled here
- [pull in Sanity's data](https://github.com/sanity-io/gatsby-source-sanity) about the routes into the build process and override the route name

**Comment by jmcbroom** [comment]
following up on this: starting to implement (2) here on the add-sanity-backend branch https://github.com/jmcbroom/multi-gtfs-gatsby/pull/24

only agency data is being successfully integrated for now, but routes shouldn't be too far behind.

**Comment by ivyrze** [comment]
This is great, thanks for working on this. If we know anything about GTFS data, it's that it's usually poorly maintained, and the Sanity backend is a clean and effective solution to that. I absolutely will be using this design pattern on future projects
